---
apiVersion: app/v1
kind: Deployment
metadate:
  name: app_deployment
spce:
  replicas: 2
  selector:
    matchLables:
      app: javawebapp
    template:
      metadate:
        name: javawebapppod
        labels:
          app: javawebapp
      spec:
        containers:
          - name: javawebappcontainer
            image: 562100/maven-web-app
            ports:
              containerPort: 8080
...
apiVersion: v1
kind: Service
metadata:
 name: javawebsvc
spec:
 type: LaodBalancer
 selector:
  app: javawebapp
 ports:
  - port: 80
    targetPort: 8080
...
